name: Lint Moonscript

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-moonscript:
    uses: CFC-Servers/github_action_workflows/.github/workflows/lint_moonscript.yml@feature/shareable
    with:
      config: "https://cfc.gg/configs/moonc/lint_config.moon"

  build-moonscript:
    uses: CFC-Servers/github_action_workflows/.github/workflows/compile_moonscript.yml@feature/shareable
