name: Create Moonscript Release

on:
  push:
    tags:
      - "*"

jobs:
  moonscript-release:
    uses: CFC-Servers/github_action_workflows/.github/workflows/moonscript_release.yml@feature/shareable
